flags = -Wall -std=c++17

runSort:
			g++ $(flags) Elguindi_Zak_QuickSort.cpp
			./a.out input.txt output.txt

runInputGenerator:
			g++ $(flags) InputFileGenerator.cpp
			./a.out input.txt output.txt


clean : 
				rm *.txt

