// Copyright 2023 CSCE240 bhipp
// compare output generated by student class member functions to expected ouptut
#include<fstream>
using std::ifstream;
#include<iostream>
using std::cout;
using std::endl;
using std::cin;
#include<string>
using std::string;

int main(int argc, char *argv[]) {
  if ( argc != 2  || argv[1][0] < '0' || argv[1][0] > '3' ) {
    cout << "Invalid test" << endl;
    return 1;
  }
  int which = argv[1][0] - '0';
  string correct[4] = { "correcttf.txt", "correctsa.txt", "correctmc1.txt",
                              "correctmc2.txt" };
  string student[4] = { "studenttf.txt", "studentsa.txt", "studentmc1.txt",
                              "studentmc2.txt" };
  string correct_file_path = "./output/" + correct[which];
  string student_file_path = "./output/" + student[which];
  ifstream correctfile(correct_file_path);
  ifstream studentfile(student_file_path);
  bool match = true;
  char correctchar, stuchar;
  int i = 0;
  cout << "Your output:" << endl;
  correctchar = correctfile.get();
  stuchar = studentfile.get();
  while ( correctfile.good() && studentfile.good() && match ) {
    match = correctchar == stuchar;
    cout << stuchar;
    if ( !match )
      cout << "<- this character should be " << correctchar << endl;
    ++i;
    correctchar = correctfile.get();
    stuchar = studentfile.get();
  }

  cout << "\n\n";
  if ( !correctfile.eof() || !studentfile.eof() || !match )
    cout << "output error at character " << i << endl;
  else
    cout << "match!" << endl;
  return 0;
}
