// Copyright 2023 CSCE240 bhipp
// compare output generated by student class member functions to expected ouptut
#include<fstream>
using std::ifstream;
#include<iostream>
using std::cout;
using std::endl;
using std::cin;
#include<string>
using std::string;
#include<cstring>
#include<cmath>

int main(int argc, char *argv[]) {
  ifstream correctfile("correctoutput.txt");
  ifstream studentfile("studentoutput.txt");
  bool match = true;
  char correctchar[501], stuchar[501];
  int totallines = 0, linescorrect = 0;
  cout << "Your output:" << endl;
  correctfile.getline(correctchar, 500);
  studentfile.getline(stuchar, 500);
  while ( correctfile.good() ) {
    if ( studentfile.good() ) {
      match = (strcmp(correctchar, stuchar) == 0);
      cout << stuchar << endl;
      if ( !match )
        cout << " - incorrect" << endl;
      else
        ++linescorrect;
      studentfile.getline(stuchar, 500);
    }
    ++totallines;
    correctfile.getline(correctchar, 500);
  }

  if ( linescorrect == totallines )
    cout << "match!" << endl;
  else
    cout << linescorrect << " of " << totallines << " lines match.\n"
         << "See correctoutput.txt and studentoutput.txt to compare." << endl;

  return 0;
}
